<?php

return ['lang' => [
	'RegistrationFormPageTitle' => 'Registration Form',
	'RegistrationFormHeader' => 'Register for TLI 2015',

	'PersonalInformationHeader' => 'Personal Information',
	'FullName' => 'Full name',
	'FullNamePlaceholder' => 'John Doe',
	'Email' => 'Email',
	'EmailPlaceholder' => 'john@example.com',
	'Phone' => 'Phone',
	'PhonePlaceholder' => '+48 555 123 456',
	'HomeClub' => 'Home club',
	'HomeClubNonMember' => "I'm not a member of Toastmasters",
	'HomeClubNotListed' => "My club is not on this list",
	'ExecCommmitteePosition' => "Executive Committee position",
	'ExecCommmitteePositionNone' => "I hold no position",
	'ExecCommmitteePositionPresident' => "President",
	'ExecCommmitteePositionVpe' => "Vice President Education",
	'ExecCommmitteePositionVpm' => "Vice President Membership",
	'ExecCommmitteePositionVppr' => "Vice President Public Relations",
	'ExecCommmitteePositionTreasurer' => "Treasurer",
	'ExecCommmitteePositionSecretary' => "Secretary",
	'ExecCommmitteePositionSaa' => "Sergeant at Arms",
	'EducationalAwards' => "Educational awards",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Choose from: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",

	'AccommodationHeader' => "Accommodation",
	'AccommodationWithToastmasters' => "Accommodation with Toastmasters",
	'AccommodationWithToastmastersHelp' => "You can choose to sleep over with a member of Toastmasters or hose an incoming guest.",
	'AccommodationWithToastmastersStay' => "I'd like to <strong>stay with</strong> a member of Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "I need accommodation on...",
	'AccommodationWithToastmastersFriSat' => "Friday/Saturday",
	'AccommodationWithToastmastersSatSun' => "Saturday/Sunday",
	'AccommodationWithToastmastersSleepOn' => "I can sleep on...",
	'AccommodationWithToastmastersSleepOnBed' => "Bed",
	'AccommodationWithToastmastersSleepOnMattress' => "Mattress",
	'AccommodationWithToastmastersSleepOnFoamPad' => "Foam pad",
	'AccommodationWithToastmastersSleepOnAnything' => "Honestly don't care as long as it's safe and warm",
	'AccommodationWithToastmastersHost' => "I'd like to <strong>host</strong> an attendee",
	'AccommodationWithToastmastersOnMyOwn' => "I'll arrange accomodation <strong>on my own</strong>",

	'EventsHeader' => "Events",
	'EventsFridaySocialYes' => "Yes, I'd love to join Friday's social event",
	'EventsSaturdayDinnerYes' => "Yes, I will participate in Saturday's dinner",
	'EventsSaturdayDinnerMeat' => "I'll have a <strong>meat</strong> meal",
	'EventsSaturdayDinnerVege' => "I'll have a <strong>vegetarian</strong> meal",
	'EventsSaturdayPartyYes' => "Yes, I will take part in Saturday's party",

	'CommentsHeader' => "Comments",
	'Comments' => "Additional comments",
	'CommentsHelp' => "Anything else you'd like to communicate or ask?",

	'SubmitAndReviewButton' => "Submit and Review",
	'SubmitAndReviewButtonHelp' => "You will have a chance to review your registration before proceeding to payment.",
]];
