<?php

return ['lang' => [
	"Yes" => "Yes",
	"No" => "No",

	'RegistrationFormPageTitle' => 'Registration Form',
	'RegistrationFormHeader' => 'Register for TLI 2015',

	'PersonalInformationHeader' => 'Personal Information',
	'FullName' => 'Full name',
	'FullNamePlaceholder' => 'John Doe',
	'FullNameValidationMsg' => "Please provide your full name.",
	'Email' => 'Email',
	'EmailPlaceholder' => 'john@example.com',
	'EmailValidationMsg' => "Please provide your email address.",
	'EmailAlertRegisteredNoPayment' => "We seem to already have your e-mail address on file, probably because you filled in this registration form earlier. Would you like to <a href=\"{0}\">proceed to payment</a> now?",
	'Phone' => 'Phone',
	'PhonePlaceholder' => '+48 555 123 456',
	'PhoneValidationMsg' => "Please provide a phone number, including the operator code and optionally, the country code. You may use dashes and spaces.",
	'HomeClub' => 'Home club',
	'HomeClubNonMember' => "I'm not a member of Toastmasters",
	'HomeClubNotListed' => "My club is not on this list",
	'HomeClubClubs' => "Clubs",
	'HomeClubCustomHelp' => "If you selected \"{0}\", enter your club name below.",
	'HomeClubCustomPlaceholder' => "Type the name of your club...",
	'HomeClubCustomValidationMsg' => "Please provide the exact name of your home club, or choose one from the list.",
	'ExecCommmitteePosition' => "Executive Committee position",
	'ExecCommmitteePositionValidationMsg' => "You selected you're not a member of Toastmasters, and yet selected an Executive Committee position. This can't be right.",
	'ExecCommmitteePosition-none' => "I hold no position",
	'ExecCommmitteePosition-president' => "President",
	'ExecCommmitteePosition-vpe' => "Vice President Education",
	'ExecCommmitteePosition-vpm' => "Vice President Membership",
	'ExecCommmitteePosition-vppr' => "Vice President Public Relations",
	'ExecCommmitteePosition-treasurer' => "Treasurer",
	'ExecCommmitteePosition-secretary' => "Secretary",
	'ExecCommmitteePosition-saa' => "Sergeant at Arms",
	'EducationalAwards' => "Educational awards",
	'EducationalAwardsNone' => "None",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Choose from: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",
	'EducationalAwardsValidationMsg' => "Please enter your educational awards from among: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM, separated by comas or spaces.",

	'AccommodationHeader' => "Accommodation",
	'AccommodationWithToastmasters' => "Accommodation with Toastmasters",
	'AccommodationWithToastmastersHelp' => "You can choose to sleep over with a member of Toastmasters or host an incoming guest.",
	'AccommodationWithToastmastersValidationMsg' => "Please choose an accommodation option.",
	'AccommodationWithToastmastersStayAnswer' => "I'd like to <strong>stay with</strong> a member of Toastmasters",
	'AccommodationWithToastmasters-stay' => "Stay with a member of Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "I need accommodation on...",
	'AccommodationWithToastmastersNeededOnValidationMsg' => "Please choose the day or days you'll need accommodation on.",
	'AccommodationWithToastmastersFriSat' => "Friday/Saturday",
	'AccommodationWithToastmasters-fri-sat' => "Friday/Saturday",
	'AccommodationWithToastmastersSatSun' => "Saturday/Sunday",
	'AccommodationWithToastmasters-sat-sun' => "Saturday/Sunday",
	'AccommodationWithToastmastersHostAnswer' => "I'd like to <strong>host</strong> an attendee",
	'AccommodationWithToastmasters-host' => "Host an attendee",
	'AccommodationWithToastmastersIndependentAnswer' => "I'll arrange accomodation <strong>on my own</strong>",
	'AccommodationWithToastmasters-independent' => "On my own",

	'EventOptionsHeader' => "Event Options",
	'EventsTranslator' => "Translator",
	'EventsTranslatorYes' => "I can act as an English-Polish-English <strong>translator</strong>",
	'EventTranslatorHelp' => "We'll give you a special badge and may ask you to help out translating some sessions for those, who don't speak their language.",
	'EventsContestYes' => "I will attend the <strong>speech contests</strong> on Friday",
	'EventsContest' => "Friday's contests",
	'EventsFridaySocial' => "Friday's social event",
	'EventsFridaySocialYes' => "I'd love to join <strong>Friday's social event</strong>",
	'EventsLunch' => "Lunch",
	'EventsLunchYes' => "I'd like to have organized <strong>lunch</strong> during the conference",
	'EventsLunchSaturday' => "on Saturday",
	'EventsLunch-saturday' => "Saturday",
	'EventsLunchSunday' => "on Sunday",
	'EventsLunch-sunday' => "Sunday",
	'EventsLunchDaysValidationMsg' => "Please choose one or both days on which you'd like to have organized lunch.",
	'EventsSaturdayDinner' => "Saturday's dinner",
	'EventsSaturdayDinnerYes' => "I will participate in <strong>Saturday's dinner</strong>",
	'EventsSaturdayDinnerMealValidationMsg' => "Please choose a meal option for the Saturday dinner.",
	'EventsSaturdayDinnerMeat' => "I'll have a <strong>meat</strong> meal",
	'EventsSaturdayDinner-meat' => "Meat",
	'EventsSaturdayDinnerVegetarian' => "I'll have a <strong>vegetarian</strong> meal",
	'EventsSaturdayDinner-vegetarian' => "Vegetarian",
	'EventsSaturdayParty' => "Saturday's party",
	'EventsSaturdayPartyYes' => "I will take part in <strong>Saturday's party</strong>",

	'CommentsHeader' => "Comments",
	'Comments' => "Additional comments",
	'CommentsNone' => "None",
	'CommentsHelp' => "Anything else you'd like to communicate or ask?",

	'SubmitAndReviewButton' => "Submit and Review",
	'SubmitAndReviewButtonHelp' => "You will have a chance to review your registration before proceeding to payment.",

	"CurrentParticipationPaymentInfo" => 'Your current participation price is <span class="label label-info">{0}</span> if paid by {1}.',
	"CurrentTotalDue" => "Your current total due payment is",

	"RegistrationReviewHeader" => "Review registration for {0}",
	"RegistrationReviewIntro" => "Please review the contents of the registration form you have just submitted, the resulting participation cost calculation and final price. If everything is correct, click the button at the bottom of the page to proceed to payment.",

	"PaymentBreakdownHeader" => "Payment breakdown",
	"PaymentBreakdownIntro" => "Based on the options you selected, your total due payment breaks down as follows:",
	"Participation" => "Participation",
	"Ticket-early" => "Early bird",
	"Ticket-regular" => "Regular",
	"Ticket-late" => "Late",
	"PaymentItemHead" => "Item",
	"PaymentTypeHead" => "Type",
	"PaymentPriceHead" => "Price",
	"PriceValidThrough" => "valid through {0}",
	"PaymentTotal" => "Grand total",

	"SelectPaymentOptionButton" => "Select payment option",

	"HowProceedToPaymentHeader" => "How can I proceed to payment?",
	"HowProceedToPaymentInfo" => "We have an existing registration for the e-mail address <strong>{0}</strong>, which hasn't been paid for yet. To let you proceed, we need to make sure it's really you, who owns the said e-mail address. Right after filling in your registration form, you received a message with a unique link that lets you access details of your registration. To proceed to payment now, please:",
	"HowProceedToPaymentStep1" => "Find the email and click the link, then",
	"HowProceedToPaymentStep2" => "Scroll down to the bottom of the page with your registration details and click the button to proceed to payment.",
	"HowProceedToPaymentHavingTroubleHeader" => "Having trouble?",
	"HowProceedToPaymentHavingTroubleInfo1" => "If you didn't receive the email with the link, please <strong>check your Spam folder</strong> first. If you still cannot find it there, we'll be happy to re-send it to you. Just click the button below and the e-mail should arrive within minutes.",
	"HowProceedToPaymentHavingTroubleResendEmail" => "Re-send e-mail",
	"HowProceedToPaymentHavingTroubleInfo2" => "If nothing helps, you have no e-mail, the link doesn't work, or anything else is wrong, please contact the person responsible for registration.",

	"EmailRegistrationConfirmationSubject" => "Registration confirmation for {0}",
	"EmailRegistrationConfirmationBody" => "We received your registration for the e-mail address {0}. You can access and review your registration at any time at: " . PHP_EOL . PHP_EOL . "{1}",

	"SendEmailSuccessHeader" => "Registration e-mail sent to {0}",
	"SendEmailSuccessInfo" => "We successfully sent an e-mail to your address at <strong>{0}</strong>. Please allow a few minutes for it to arrive.",

	"SendEmailProblemHeader" => "Problem sending email to {0}",
	"SendEmailProblemInfo" => "Sorry about that. There's been some hiccup on the way and we couldn't get your e-mail out to <strong>{0}</strong>. This may be a one-time problem, so before calling the cavalry please do try this one more time by clicking the button below. If you get to this very same page, contact the person responsible for registration.",

	"RegistrationsListHeader" => "Registrations list",
	"RegistrationsListIntro" => "We currently have {0} registrations on file, {1} of which are paid. Last registration was on {2}.",

	"DateEntered" => "Date entered",
	"DatePaid" => "Date paid",

	"SignInHeader" => "Please sign in",
	"Password" => "Password",
	"SignInButton" => "Sign in",
	"LogoutButton" => "Logout",
	"SignedInAs" => "Signed in as {0}",
]];
