<?php

return ['lang' => [
	"Yes" => "Yes",
	"No" => "No",

	'RegistrationFormPageTitle' => 'Registration Form',
	'RegistrationFormHeader' => 'Register for TLI 2015',

	'PersonalInformationHeader' => 'Personal Information',
	'FullName' => 'Full name',
	'FullNamePlaceholder' => 'John Doe',
	'Email' => 'Email',
	'EmailPlaceholder' => 'john@example.com',
	'EmailAlertRegisteredNoPayment' => "We seem to already have your e-mail address on file, probably because you filled in this registration form earlier. Would you like to <a href=\"{0}\">proceed to payment</a> now?",
	'Phone' => 'Phone',
	'PhonePlaceholder' => '+48 555 123 456',
	'HomeClub' => 'Home club',
	'HomeClubNonMember' => "I'm not a member of Toastmasters",
	'HomeClubNotListed' => "My club is not on this list",
	'ExecCommmitteePosition' => "Executive Committee position",
	'ExecCommmitteePosition-none' => "I hold no position",
	'ExecCommmitteePosition-president' => "President",
	'ExecCommmitteePosition-vpe' => "Vice President Education",
	'ExecCommmitteePosition-vpm' => "Vice President Membership",
	'ExecCommmitteePosition-vppr' => "Vice President Public Relations",
	'ExecCommmitteePosition-treasurer' => "Treasurer",
	'ExecCommmitteePosition-secretary' => "Secretary",
	'ExecCommmitteePosition-saa' => "Sergeant at Arms",
	'EducationalAwards' => "Educational awards",
	'EducationalAwardsNone' => "None",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Choose from: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",

	'AccommodationHeader' => "Accommodation",
	'AccommodationWithToastmasters' => "Accommodation with Toastmasters",
	'AccommodationWithToastmastersHelp' => "You can choose to sleep over with a member of Toastmasters or hose an incoming guest.",
	'AccommodationWithToastmastersStayAnswer' => "I'd like to <strong>stay with</strong> a member of Toastmasters",
	'AccommodationWithToastmasters-stay' => "Stay with a member of Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "I need accommodation on...",
	'AccommodationWithToastmastersFriSat' => "Friday/Saturday",
	'AccommodationWithToastmasters-fri-sat' => "Friday/Saturday",
	'AccommodationWithToastmastersSatSun' => "Saturday/Sunday",
	'AccommodationWithToastmasters-sat-sun' => "Saturday/Sunday",
	'AccommodationWithToastmastersSleepOn' => "I can sleep on...",
	'AccommodationWithToastmastersSleepOn-bed' => "Bed",
	'AccommodationWithToastmastersSleepOn-mattress' => "Mattress",
	'AccommodationWithToastmastersSleepOn-foam-pad' => "Foam pad",
	'AccommodationWithToastmastersSleepOnAnything' => "Honestly don't care as long as it's safe and warm",
	'AccommodationWithToastmastersSleepOn-anything' => "Don't care",
	'AccommodationWithToastmastersHostAnswer' => "I'd like to <strong>host</strong> an attendee",
	'AccommodationWithToastmasters-host' => "Host an attendee",
	'AccommodationWithToastmastersIndependentAnswer' => "I'll arrange accomodation <strong>on my own</strong>",
	'AccommodationWithToastmasters-independent' => "On my own",

	'EventsHeader' => "Events",
	'EventsFridaySocial' => "Friday's social event",
	'EventsFridaySocialYes' => "Yes, I'd love to join Friday's social event",
	'EventsSaturdayDinner' => "Saturday's dinner",
	'EventsSaturdayDinnerYes' => "Yes, I will participate in Saturday's dinner",
	'EventsSaturdayDinnerMeat' => "I'll have a <strong>meat</strong> meal",
	'EventsSaturdayDinner-meat' => "Meat",
	'EventsSaturdayDinnerVegetarian' => "I'll have a <strong>vegetarian</strong> meal",
	'EventsSaturdayDinner-vegetarian' => "Vegetarian",
	'EventsSaturdayParty' => "Saturday's party",
	'EventsSaturdayPartyYes' => "Yes, I will take part in Saturday's party",

	'CommentsHeader' => "Comments",
	'Comments' => "Additional comments",
	'CommentsNone' => "None",
	'CommentsHelp' => "Anything else you'd like to communicate or ask?",

	'SubmitAndReviewButton' => "Submit and Review",
	'SubmitAndReviewButtonHelp' => "You will have a chance to review your registration before proceeding to payment.",

	"RegistrationReviewHeader" => "Review registration for {0}",
	"RegistrationReviewIntro" => "Please review the contents of the registration form you have just submitted, the resulting participation cost calculation and final price. If everything is correct, click the button at the bottom of the page to proceed to payment.",

	"PaymentBreakdownHeader" => "Payment breakdown",
	"Participation" => "Participation",
	"TicketEarly" => "Early bird",
	"TicletRegular" => "Regular",
	"TicketLate" => "Late",
	"PaymentItemHead" => "Item",
	"PaymentTypeHead" => "Type",
	"PaymentPriceHead" => "Price",
	"PaymentTotal" => "Grand total",

	"SelectPaymentOptionButton" => "Select payment option",

	"HowProceedToPaymentHeader" => "How can I proceed to payment?",
	"HowProceedToPaymentInfo" => "We have an existing registration for the e-mail address <strong>{0}</strong>, which hasn't been paid for yet. To let you proceed, we need to make sure it's really you, who owns the said e-mail address. Right after filling in your registration form, you received a message with a unique link that lets you access details of your registration. To proceed to payment now, please:",
	"HowProceedToPaymentStep1" => "Find the email and click the link, then",
	"HowProceedToPaymentStep2" => "Scroll down to the bottom of the page with your registration details and click the button to proceed to payment.",
	"HowProceedToPaymentHavingTroubleHeader" => "Having trouble?",
	"HowProceedToPaymentHavingTroubleInfo1" => "If you didn't receive the email with the link, please <strong>check your Spam folder</strong> first. If you still cannot find it there, we'll be happy to re-send it to you. Just click the button below and the e-mail should arrive within minutes.",
	"HowProceedToPaymentHavingTroubleResendEmail" => "Re-send e-mail",
	"HowProceedToPaymentHavingTroubleInfo2" => "If nothing helps, you have no e-mail, the link doesn't work, or anything else is wrong, please contact the person responsible for registration.",
]];
