<?php

return ['lang' => [
	"Yes" => "Tak",
	"No" => "Nie",

	'RegistrationFormPageTitle' => 'Formularz rejestracyjny',
	'RegistrationFormHeader' => 'Rejestracja na TLI 2015',

	'PersonalInformationHeader' => 'Informacje osobiste',
	'FullName' => 'Imię i nazwisko',
	'FullNamePlaceholder' => 'Jan Kowalski',
	'FullNameValidationMsg' => "Podaj swoje imię i nazwisko.",
	'Email' => 'Email',
	'EmailPlaceholder' => 'jan@example.com',
	'EmailValidationMsg' => "Podaj swój adres email.",
	'EmailAlertRegisteredNoPayment' => "Wygląda na to, że mamy już zapisany twój adres e-mail, prawdopodobnie z wcześniej wypełnionej rejestracji. Czy chcesz <a href=\"{0}\">przejść teraz do płatności</a>?",
	'Phone' => 'Telefon',
	'PhonePlaceholder' => '+48 555 123 456',
	'PhoneValidationMsg' => "Podaj swój numer telefonu, włącznie z kodem operatora i opcjonalnie poprzedzony kodem kraju. Możesz podzielić numer spacjami lub myślnikami.",
	'HomeClub' => 'Klub Toastmasters',
	'HomeClubNonMember' => "Nie jestem członkiem Toastmasters",
	'HomeClubNotListed' => "Mojego klubu nie ma na liście",
	'HomeClubClubs' => "Kluby",
	'HomeClubCustomHelp' => "Przy wyborze opcji \"{0}\", wpisz naszę klubu poniżej.",
	'HomeClubCustomPlaceholder' => "Wpisz nazwę swojego klubu...",
	'HomeClubCustomValidationMsg' => "Podaj dokładną nazwę swojego klubu, lub wybierz klub z listy.",
	'ExecCommmitteePosition' => "Pozycja w Zarządzie klubu",
	'ExecCommmitteePositionValidationMsg' => "Twój wcześniejszy wybór wskazuje, że nie należysz do Toastmasters, więc nie możesz zajmować pozycji w Zarządzie klubu.",
	'ExecCommmitteePosition-none' => "Nie jestem członkiem zarządu",
	'ExecCommmitteePosition-president' => "Prezes",
	'ExecCommmitteePosition-vpe' => "Wiceprezes ds. Edukacji",
	'ExecCommmitteePosition-vpm' => "Wiceprezes ds. Członkostwa",
	'ExecCommmitteePosition-vppr' => "Wiceprezes ds. Public Relations",
	'ExecCommmitteePosition-treasurer' => "Skarbnik",
	'ExecCommmitteePosition-secretary' => "Sekretarz",
	'ExecCommmitteePosition-saa' => "Dyrektor Administracyjny",
	'EducationalAwards' => "Osiągnięcia edukacyjne",
	'EducationalAwardsNone' => "Brak",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Wpisz spośród: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",
	'EducationalAwardsValidationMsg' => "Wpisz swoje nagrody spośród: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM, oddzielone przecinkami lub spacjami.",

	'AccommodationHeader' => "Zakwaterowanie",
	'AccommodationWithToastmasters' => "Zakwaterowanie u członków Toastmasters",
	'AccommodationWithToastmastersHelp' => "Możesz wybrać nocleg u członków Toastmasters lub zadeklarować, że przyjmiesz kogoś z przyjeznych gości.",
	'AccommodationWithToastmastersValidationMsg' => "Wybierz jedną z opcji zakwaterowania.",
	'AccommodationWithToastmastersStayAnswer' => "Proszę o <strong>nocleg u członków</strong> Toastmasters",
	'AccommodationWithToastmasters-stay' => "Nocleg u członków Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "Potrzebuję noclegu z...",
	'AccommodationWithToastmastersNeededOnValidationMsg' => "Wybierz dzień lub dni, w których będziesz potrzebować zakwaterowania.",
	'AccommodationWithToastmastersFriSat' => "piątku na sobotę",
	'AccommodationWithToastmasters-fri-sat' => "piątku na sobotę",
	'AccommodationWithToastmastersSatSun' => "soboty na niedzielę",
	'AccommodationWithToastmasters-sat-sun' => "soboty na niedzielę",
	'AccommodationWithToastmastersHostAnswer' => "Mogę <strong>przyjąć przyjezdnego</strong> na nocleg",
	'AccommodationWithToastmasters-host' => "Mogę przyjąć przyjezdnego",
	'AccommodationWithToastmastersIndependent' => "<strong>Samemu zorganizuję</strong> swój nocleg",
	'AccommodationWithToastmasters-independent' => "Samemu zorganizuję swój nocleg",

	'EventOptionsHeader' => "Opcje wydarzenia",
	'EventsTranslator' => "Tłumacz",
	'EventsTranslatorYes' => "Chętnie pomogę jako <strong>tłumacz</strong> polsko-angielsko-polski",
	'EventTranslatorHelp' => "Otrzymasz specjalny identyfikator i możemy poprosić cię o tłumaczenie sesji dla osób, które nie znają jej języka.",
	'EventsContestYes' => "Przyjdę na <strong>konkursy przemówień</strong> w piątek",
	'EventsContest' => "Piątkowe konkursy",
	'EventsFridaySocialYes' => "Chętnie wezmę udział w <strong>piątkowym wydarzeniu</strong>",
	'EventsFridaySocial' => "Piątkowe wydarzenie",
	'EventsLunch' => "Zjem <strong>lunch</strong> zorganizowany przez konferencję",
	'EventsLunchSaturday' => "w sobotę",
	'EventsLunch-saturday' => "sobota",
	'EventsLunchSunday' => "w niedzielę",
	'EventsLunch-sunday' => "niedziela",
	'EventsLunchDaysValidationMsg' => "Wybierz jeden lub oba dni, w których zjesz zorganizowany lunch.",
	'EventsSaturdayDinner' => "Sobotnia kolacja",
	'EventsSaturdayDinnerYes' => "Wezmę udział w sobotniej kolacji",
	'EventsSaturdayDinnerMealValidationMsg' => "Wybierz swój posiłek podczas <strong>sobotniej kolacji</strong>.",
	'EventsSaturdayDinnerMeat' => "Poproszę o <strong>mięsne</strong> danie",
	'EventsSaturdayDinner-meat' => "Mięsne",
	'EventsSaturdayDinnerVegetarian' => "Poproszę o <strong>wegetariańskie</strong> danie",
	'EventsSaturdayDinner-vegetarian' => "Wegetariańskie",
	'EventsSaturdayParty' => "Sobotnia impreza",
	'EventsSaturdayPartyYes' => "Wezmę udział w <strong>sobotniej imprezie</strong>",

	'CommentsHeader' => "Komentarze",
	'Comments' => "Dodatkowe komentarze",
	'CommentsNone' => "Brak",
	'CommentsHelp' => "Czy coś jeszcze chcesz przekazać lub o coś spytać?",

	'SubmitAndReviewButton' => "Wyślij i potwierdź",
	'SubmitAndReviewButtonHelp' => "Możesz jeszcze raz sprawdzić swoje zgłoszenie zanim przejdziesz do płatności.",

	"CurrentParticipationPaymentInfo" => 'Aktualna cena za uczestnictwo w konferencji wynosi <span class="label label-info">{0}</span> ({1}) i obowiązuje dla płatności do {2}.',
	"CurrentTotalDue" => "Twoja aktualna należność to",

	"RegistrationReviewHeader" => "Podsumowanie rejestracji dla {0}",
	"RegistrationReviewIntro" => "Sprawdź informacje, które otrzymaliśmy od ciebie w trakcie rejestracji i podsumowanie kosztu rejestracji na dole strony. Jeśli wszystko się zgadza, kliknij przycisk na dole strony aby przejść do płatności.",

	"PaymentBreakdownHeader" => "Podsumowanie płatności",
	"PaymentBreakdownIntro" => "W oparciu o wybrane przez ciebie opcje, opłata przedstawia sie następująco:",
	"Participation" => "Uczestnictwo",
	"Ticket-early" => "Wczesny",
	"Ticket-regular" => "Normalny",
	"Ticket-late" => "Późny",
	"PaymentItemHead" => "Pozycja",
	"PaymentTypeHead" => "Typ",
	"PaymentPriceHead" => "Cena",
	"PriceValidThrough" => "ważny do {0}",
	"PaymentTotal" => "Suma",

	"SelectPaymentOptionButton" => "Wybierz sposób płatności",

	"HowProceedToPaymentHeader" => "Jak przejść do płatności?",
	"HowProceedToPaymentInfo" => "Mamy już zapisaną rejestrację dla adresu e-mail <strong>{0}</strong>, która nie została jeszcze opłacona. Aby umożliwić ci teraz dokonanie opłaty, musimy najpierw upewnić się, że podany adres e-mail należy do ciebie. Zaraz po wypełnieniu formularza wysłaliśmy ci e-mail z odnośnikiem, który pozwala otworzyć szczegóły rejestracji. Aby zapłacić teraz:",
	"HowProceedToPaymentStep1" => "Znajdź wiadomość e-mail z odnośnikiem, i",
	"HowProceedToPaymentStep2" => "Kliknij przycisk na dole strony z danymi rejestracji, aby dokonać płatności.",
	"HowProceedToPaymentHavingTroubleHeader" => "Problemy?",
	"HowProceedToPaymentHavingTroubleInfo1" => "Jeśli e-mail z odnośnikiem w ogóle do ciebie nie dotarł, najpierw <strong>sprawdź swój folder ze Spamem</strong>. Jeśli tam też go nie ma, chętnie prześlemy ci go ponownie. Kliknij przycisk poniżej, a e-mail powinien dotrzeć w ciągu kilku minut.",
	"HowProceedToPaymentHavingTroubleResendEmail" => "Wyślij e-mail ponownie",
	"HowProceedToPaymentHavingTroubleInfo2" => "Jeśli nic nie pomaga, nie dostajesz wiadomości, odnośnik nie działa lub cokolwiek innego sprawia ci problemy, skontaktuj się z osobą odpowiedzialną za rejestrację.",

	"EmailRegistrationConfirmationSubject" => "Potwierdzenie rejestracji dla {0}",
	"EmailRegistrationConfirmationBody" => "Przyjęliśmy twoją rejestrację dla adresu e-mail {0}. Możesz wrócić do niej w każdej chwili pod adresem: " . PHP_EOL . PHP_EOL . "{1}",

	"SendEmailSuccessHeader" => "Email wysłany do {0}",
	"SendEmailSuccessInfo" => "Email z informacją o rejestracji został wysłany pod adres <strong>{0}</strong>. Powinien dotrzeć w przeciągu kilku minut.",

	"SendEmailProblemHeader" => "Problem przy wysyłaniu maila do {0}",
	"SendEmailProblemInfo" => "Przepraszamy serdecznie. Coś po drodze odbiło się czkawką i nie byliśmy w stanie wysłać maila pod twój adres <strong>{0}</strong>. To może być jednorazowy problem, więc zanim zadzwonisz po kawalerię, spróbuj jeszcze raz klikając na przycisk poniżej. Jeśli wrócisz na tą samą stronę, skontaktuj się z osobą odpowiedzialną za rejestrację",

	"RegistrationsListHeader" => "Lista rejestracji",
	"RegistrationsListIntro" => "Mamy aktualnie {0} rejestracji.",

	"DateEntered" => "Data wpisania",
	"DatePaid" => "Data opłacenia",

	"Password" => "Hasło",
	"SignInButton" => "Zaloguj",
	"LogoutButton" => "Wyloguj",
	"SignedInAs" => "Zalogowany jako {0}",
]];
