<?php

return ['lang' => [
	'RegistrationFormPageTitle' => 'Formularz rejestracyjny',
	'RegistrationFormHeader' => 'Rejestracja na TLI 2015',

	'PersonalInformationHeader' => 'Informacje osobiste',
	'FullName' => 'Imię i nazwisko',
	'FullNamePlaceholder' => 'Jan Kowalski',
	'Email' => 'Email',
	'EmailPlaceholder' => 'jan@example.com',
	'Phone' => 'Telefon',
	'PhonePlaceholder' => '+48 555 123 456',
	'HomeClub' => 'Klub Toastmasters',
	'HomeClubNonMember' => "Nie jestem członkiem Toastmasters",
	'HomeClubNotListed' => "Mojego klubu nie ma na liście",
	'ExecCommmitteePosition' => "Pozycja w Zarządzie klubu",
	'ExecCommmitteePositionNone' => "Nie jestem członkiem zarządu",
	'ExecCommmitteePositionPresident' => "Prezes",
	'ExecCommmitteePositionVpe' => "Wiceprezes ds. Edukacji",
	'ExecCommmitteePositionVpm' => "Wiceprezes ds. Członkostwa",
	'ExecCommmitteePositionVppr' => "Wiceprezes ds. Public Relations",
	'ExecCommmitteePositionTreasurer' => "Skarbnik",
	'ExecCommmitteePositionSecretary' => "Sekretarz",
	'ExecCommmitteePositionSaa' => "Dyrektor Administracyjny",
	'EducationalAwards' => "Osiągnięcia edukacyjne",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Wpisz spośród: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",

	'AccommodationHeader' => "Zakwaterowanie",
	'AccommodationWithToastmasters' => "Zakwaterowanie u członków Toastmasters",
	'AccommodationWithToastmastersHelp' => "Możesz wybrać nocleg u członków Toastmasters lub zadeklarować, że przyjmiesz kogoś z przyjeznych gości.",
	'AccommodationWithToastmastersStay' => "Proszę o <strong>nocleg u członków</strong> Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "Potrzebuję noclegu z...",
	'AccommodationWithToastmastersFriSat' => "piątku na sobotę",
	'AccommodationWithToastmastersSatSun' => "soboty na niedzielę",
	'AccommodationWithToastmastersSleepOn' => "Mogę spać na...",
	'AccommodationWithToastmastersSleepOnBed' => "łóżku",
	'AccommodationWithToastmastersSleepOnMattress' => "materacu",
	'AccommodationWithToastmastersSleepOnFoamPad' => "karimacie",
	'AccommodationWithToastmastersSleepOnAnything' => "czymkolwiek, byle było bezpiecznie i ciepło",
	'AccommodationWithToastmastersHost' => "Mogę <strong>przyjąć przyjezdnego</strong> na nocleg",
	'AccommodationWithToastmastersOnMyOwn' => "<strong>Samemu zorganizuję</strong> swój nocleg",

	'EventsHeader' => "Wydarzenia",
	'EventsFridaySocialYes' => "Tak, chętnie wezmę udział w piątkowym wydarzeniu",
	'EventsSaturdayDinnerYes' => "Tak, wezmę udział w sobotniej kolacji",
	'EventsSaturdayDinnerMeat' => "Poproszę o <strong>mięsne</strong> danie",
	'EventsSaturdayDinnerVege' => "Poproszę o <strong>wegetariańskie</strong> danie",
	'EventsSaturdayPartyYes' => "Tak, wezmę udział w sobotniej imprezie",

	'CommentsHeader' => "Komentarze",
	'Comments' => "Dodatkowe komentarze",
	'CommentsHelp' => "Czy coś jeszcze chcesz przekazać lub o coś spytać?",

	'SubmitAndReviewButton' => "Wyślij i potwierdź",
	'SubmitAndReviewButtonHelp' => "Możesz jeszcze raz sprawdzić swoje zgłoszenie zanim przejdziesz do płatności.",
]];
