<?php

return ['lang' => [
	"Yes" => "Tak",
	"No" => "Nie",

	'RegistrationFormPageTitle' => 'Formularz rejestracyjny',
	'RegistrationFormHeader' => 'Rejestracja na TLI 2015',

	'PersonalInformationHeader' => 'Informacje osobiste',
	'FullName' => 'Imię i nazwisko',
	'FullNamePlaceholder' => 'Jan Kowalski',
	'Email' => 'Email',
	'EmailPlaceholder' => 'jan@example.com',
	'EmailAlertRegisteredNoPayment' => "Wygląda na to, że mamy już zapisany twój adres e-mail, prawdopodobnie z wcześniej wypełnionej rejestracji. Czy chcesz <a href=\"{0}\">przejść teraz do płatności</a>?",
	'Phone' => 'Telefon',
	'PhonePlaceholder' => '+48 555 123 456',
	'HomeClub' => 'Klub Toastmasters',
	'HomeClubNonMember' => "Nie jestem członkiem Toastmasters",
	'HomeClubNotListed' => "Mojego klubu nie ma na liście",
	'ExecCommmitteePosition' => "Pozycja w Zarządzie klubu",
	'ExecCommmitteePosition-none' => "Nie jestem członkiem zarządu",
	'ExecCommmitteePosition-president' => "Prezes",
	'ExecCommmitteePosition-vpe' => "Wiceprezes ds. Edukacji",
	'ExecCommmitteePosition-vpm' => "Wiceprezes ds. Członkostwa",
	'ExecCommmitteePosition-vppr' => "Wiceprezes ds. Public Relations",
	'ExecCommmitteePosition-treasurer' => "Skarbnik",
	'ExecCommmitteePosition-secretary' => "Sekretarz",
	'ExecCommmitteePosition-saa' => "Dyrektor Administracyjny",
	'EducationalAwards' => "Osiągnięcia edukacyjne",
	'EducationalAwardsNone' => "Brak",
	'EducationalAwardsPlaceholder' => "CC, ALB",
	'EducationalAwardsTitle' => "Wpisz spośród: CC, ACB, ACS, ACG, CL, ALB, ALS, DTM",

	'AccommodationHeader' => "Zakwaterowanie",
	'AccommodationWithToastmasters' => "Zakwaterowanie u członków Toastmasters",
	'AccommodationWithToastmastersHelp' => "Możesz wybrać nocleg u członków Toastmasters lub zadeklarować, że przyjmiesz kogoś z przyjeznych gości.",
	'AccommodationWithToastmastersStayAnswer' => "Proszę o <strong>nocleg u członków</strong> Toastmasters",
	'AccommodationWithToastmasters-stay' => "Nocleg u członków Toastmasters",
	'AccommodationWithToastmastersNeededOn' => "Potrzebuję noclegu z...",
	'AccommodationWithToastmastersFriSat' => "piątku na sobotę",
	'AccommodationWithToastmasters-fri-sat' => "piątku na sobotę",
	'AccommodationWithToastmastersSatSun' => "soboty na niedzielę",
	'AccommodationWithToastmasters-sat-sun' => "soboty na niedzielę",
	'AccommodationWithToastmastersSleepOn' => "Mogę spać na...",
	'AccommodationWithToastmastersSleepOn-bed' => "łóżku",
	'AccommodationWithToastmastersSleepOn-mattress' => "materacu",
	'AccommodationWithToastmastersSleepOn-foam-pad' => "karimacie",
	'AccommodationWithToastmastersSleepOnAnything' => "czymkolwiek, byle było bezpiecznie i ciepło",
	'AccommodationWithToastmastersSleepOn-anything' => "czymkolwiek, byle było bezpiecznie i ciepło",
	'AccommodationWithToastmastersHostAnswer' => "Mogę <strong>przyjąć przyjezdnego</strong> na nocleg",
	'AccommodationWithToastmasters-host' => "Mogę przyjąć przyjezdnego",
	'AccommodationWithToastmastersIndependent' => "<strong>Samemu zorganizuję</strong> swój nocleg",
	'AccommodationWithToastmasters-independent' => "Samemu zorganizuję swój nocleg",

	'EventsHeader' => "Wydarzenia",
	'EventsFridaySocialYes' => "Tak, chętnie wezmę udział w piątkowym wydarzeniu",
	'EventsFridaySocial' => "Piątkowe wydarzenie",
	'EventsSaturdayDinner' => "Sobotnia kolacja",
	'EventsSaturdayDinnerYes' => "Tak, wezmę udział w sobotniej kolacji",
	'EventsSaturdayDinnerMeat' => "Poproszę o <strong>mięsne</strong> danie",
	'EventsSaturdayDinner-meat' => "Mięsne",
	'EventsSaturdayDinnerVegetarian' => "Poproszę o <strong>wegetariańskie</strong> danie",
	'EventsSaturdayDinner-vegetarian' => "Wegetariańskie",
	'EventsSaturdayParty' => "Sobotnia impreza",
	'EventsSaturdayPartyYes' => "Tak, wezmę udział w sobotniej imprezie",

	'CommentsHeader' => "Komentarze",
	'Comments' => "Dodatkowe komentarze",
	'CommentsNone' => "Brak",
	'CommentsHelp' => "Czy coś jeszcze chcesz przekazać lub o coś spytać?",

	'SubmitAndReviewButton' => "Wyślij i potwierdź",
	'SubmitAndReviewButtonHelp' => "Możesz jeszcze raz sprawdzić swoje zgłoszenie zanim przejdziesz do płatności.",

	"RegistrationReviewHeader" => "Podsumowanie rejestracji dla {0}",
	"RegistrationReviewIntro" => "Sprawdź informacje, które otrzymaliśmy od ciebie w trakcie rejestracji i podsumowanie kosztu rejestracji na dole strony. Jeśli wszystko się zgadza, kliknij przycisk na dole strony aby przejść do płatności.",

	"PaymentBreakdownHeader" => "Podsmowanie płatności",
	"Participation" => "Uczestnictwo",
	"TicketEarly" => "Wczesny",
	"TicletRegular" => "Normalny",
	"TicketLate" => "Późny",
	"PaymentItemHead" => "Pozycja",
	"PaymentTypeHead" => "Typ",
	"PaymentPriceHead" => "Cena",
	"PaymentTotal" => "Suma",

	"SelectPaymentOptionButton" => "Wybierz sposób płatności",

	"HowProceedToPaymentHeader" => "Jak przejść do płatności?",
	"HowProceedToPaymentInfo" => "Mamy już zapisaną rejestrację dla adresu e-mail <strong>{0}</strong>, która nie została jeszcze opłacona. Aby umożliwić ci teraz dokonanie opłaty, musimy najpierw upewnić się, że podany adres e-mail należy do ciebie. Zaraz po wypełnieniu formularza wysłaliśmy ci e-mail z odnośnikiem, który pozwala otworzyć szczegóły rejestracji. Aby zapłacić teraz:",
	"HowProceedToPaymentStep1" => "Znajdź wiadomość e-mail z odnośnikiem, i",
	"HowProceedToPaymentStep2" => "Kliknij przycisk na dole strony z danymi rejestracji, aby dokonać płatności.",
	"HowProceedToPaymentHavingTroubleHeader" => "Problemy?",
	"HowProceedToPaymentHavingTroubleInfo1" => "Jeśli e-mail z odnośnikiem w ogóle do ciebie nie dotarł, najpierw <strong>sprawdź swój folder ze Spamem</strong>. Jeśli tam też go nie ma, chętnie prześlemy ci go ponownie. Kliknij przycisk poniżej, a e-mail powinien dotrzeć w ciągu kilku minut.",
	"HowProceedToPaymentHavingTroubleResendEmail" => "Wyślij e-mail ponownie",
	"HowProceedToPaymentHavingTroubleInfo2" => "Jeśli nic nie pomaga, nie dostajesz wiadomości, odnośnik nie działa lub cokolwiek innego sprawia ci problemy, skontaktuj się z osobą odpowiedzialną za rejestrację.",

	"EmailRegistrationConfirmationSubject" => "Potwierdzenie rejestracji dla {0}",
	"EmailRegistrationConfirmationBody" => "Przyjęliśmy twoją rejestrację dla adresu e-mail {0}. Możesz wrócić do niej w każdej chwili pod adresem: " . PHP_EOL . PHP_EOL . "{1}",

	"SendEmailProblemHeader" => "Problem przy wysyłaniu maila do {0}",
	"SendEmailProblemInfo" => "Przepraszamy serdecznie. Coś po drodze odbiło się czkawką i nie byliśmy w stanie wysłać maila pod twój adres <strong>{0}</strong>. To może być jednorazowy problem, więc zanim zadzwonisz po kawalerię, spróbuj jeszcze raz klikając na przycisk poniżej. Jeśli wrócisz na tą samą stronę, skontaktuj się z osobą odpowiedzialną za rejestrację",

	"RegistrationsListHeader" => "Lista rejestracji",
	"RegistrationsListIntro" => "Mamy aktualnie {0} rejestracji.",

	"DateEntered" => "Data wpisania",
	"DatePaid" => "Data opłacenia",

	"SignInHeader" => "Zaloguj się",
	"Password" => "Hasło",
	"SignInButton" => "Zaloguj",
	"LogoutButton" => "Wyloguj",
	"SignedInAs" => "Zalogowany jako {0}",
]];
